version: "3.8"
services:
  frontend:
    image: frontend:local
    container_name: frontend
    restart: always
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    ports:
      - 5002:5000
