version: "3.8"

services:

  client:
    image: client:local
    container_name: client
    restart: always
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    ports:
      - 5002:5000
