pipeline {
    agent any

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        skipStagesAfterUnstable()
    }

    stages {
        stage("Test") {
            steps {
                echo "Hello world"
            }
        }
    }
}