pipeline {
    agent any

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        skipStagesAfterUnstable()
    }

    stages {
        stage('Build') {
            steps {
            }
        }

        stage('Test') {
            steps {
            }
        }

        stage('Acceptance Test') {
            steps {
            }
        }

        stage('Deploy') {
            steps {
            }
        }
    }

    post {
        always {
            deleteDir()
        }
    }
}
