@startuml DeploymentDiagram

' Declaration
' node ASP
' node Client
' node Server
node "MySQL Server" as MySQL <<device>> {
  database DataBase
}

note left of MySQL
My SQL Server
<code>
  - Tier: Basic Gen5
  - Storage: 5GB
Price compute: $0.176/hour
Price storage: $0.115/GB/month
</code>
end note

node "Storage Account Service" <<device>> as SA {
  storage Storage
}

note right of SA
Storage Account
<code>
  - Tier: Standard
Price: $0.15/GB/month
</code>
end note

node "PC" <<device>> {
  component "Web Browser" as WB
}

node "Mobile" <<device>> {
  component "Mobile Browser" as MB
  component "Mobile Application" as MA
}

' Dependency
node "App Service Plan" <<device>> as ASP {
  component "App Service2" as AP2 {
    frame "AS2_Docker Container1" as DC2 {
      component "Web service API\n      (API App)" as Server
    }
  }

  component "App Service1" as AP1 {
    frame "AS1_Docker Container1" as DC1 {
      component "Web Server\n (Web App)" as Client
    }
  }
}

note left of ASP
App Service Plan
<code>
  - Tier: Basic
  - Worker Size: Medium
  - Number of Workers: 1
Price compute: $0.15/hour
</code>
end note


Client - Server: <<HTTP>>
Server -u- MySQL: <<JDBC>>
Server -u- SA: <<HTTP>>

WB -u- Client: <<HTTP>>
MB -u- Client: <<HTTP>>
MA -u- Server: <<HTTP>>

@enduml
