version: "3.8"
services:
  thesisapi:
    image: thesisapi:${DC_PROJECT_VERSION:-local}
    container_name: thesisapi
    restart: always
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mysql
    environment:
      - SERVER_PORT=5000
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/thesis
      - SPRING_DATASOURCE_USERNAME=${DC_MYSQL_USERNAME:-admindev}
      - SPRING_DATASOURCE_PASSWORD=${DC_MYSQL_PASSWORD:-admindev}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL5InnoDBDialect

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 5001:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DC_MYSQL_ROOT_PASSWORD:-1234}
      - MYSQL_USER=${DC_MYSQL_USERNAME:-admindev}
      - MYSQL_PASSWORD=${DC_MYSQL_PASSWORD:-admindev}
      - MYSQL_DATABASE=thesis
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
