spring:
  datasource:
    username: admindev
    password: admindev
    url: jdbc:mysql://localhost:3306/thesis
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 5000
  servlet:
    contextPath: /api
